[platformio]
default_envs = cyd_gateway, antenna_node_1, antenna_node_2
src_dir = firmware

[env]
platform = espressif32
framework = arduino
board = esp32dev
monitor_speed = 115200

[env:cyd_gateway]
build_src_filter =
    +<cyd_gateway_hello.cpp>
lib_deps =
    bodmer/TFT_eSPI
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
build_flags =
    -D USER_SETUP_LOADED
    -D ILI9341_2_DRIVER
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D USE_HSPI_PORT
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D SPI_FREQUENCY=27000000L

[env:antenna_node_base]
build_src_filter =
    +<antenna_node_hello.cpp>

[env:antenna_node_1]
extends = env:antenna_node_base
build_flags =
    -D ANTENNA_NODE_ID=1

[env:antenna_node_2]
extends = env:antenna_node_base
lib_deps =
    adafruit/Adafruit LIS2MDL@^2.1.8
    adafruit/Adafruit LSM303 Accel@^1.1.9
build_flags =
    -D ANTENNA_NODE_ID=2
    -D ANTENNA_NODE_HAS_LSM303AGR=1
